### ISSUE TITLE
首页的刷新功能，刷新后页面路径改变，页面出现错误

### ISSUE THREAD

**Issue by shaojunmei0102** [microapp-store/linjiashop#28]
刷新前路径：http://localhost:9528/#/dashboard
刷新后路径：http://localhost:9528/#/redirect/dashboard
多了路径：/redirect

**Comment by enilu** [comment]
已修复 https://github.com/microapp-store/linjiashop/commit/77d5f76b169ec865372873eccaa4ad1ddc3d1e13
