### ISSUE TITLE
数据混乱

### ISSUE THREAD

**Issue by weibangzhuo** [microapp-store/linjiashop#41]
后台菜单被人乱操作，有些菜单跟之前看的一不一样，希望能恢复一下数据，移动端打开商品报错
![image](https://user-images.githubusercontent.com/37473232/146670083-c119c185-654e-4834-9ba1-e4f47439bfde.png)

**Comment by enilu** [comment]
已修复

**Comment by burnszp** [comment]
你好，你的邮件我已经收到。
