### ISSUE TITLE
将图片存放到配置的目录下

### ISSUE THREAD

**Issue by Ravanla** [microapp-store/linjiashop#47]
将图片存放到t_sys_cfg表中system.file.upload.path配置的目录下不懂这个绝对路径怎么找

**Comment by burnszp** [comment]
你好，你的邮件我已经收到。

**Comment by Ravanla** [comment]
大佬，/data/flash-waimai/runtime/upload 这里是哪，我的flash-waimai没有runtime，或者sql data目录也没有

**Comment by enilu** [comment]
自己随便创建，想创建到哪里就放到哪里，比如你在C盘创建了一个目录c:\\upload,那你，就在系统参数表t_sys_cfg表里更新下，cfg_name=“system.file.upload.path”的那条记录

**Comment by Ravanla** [comment]
好的，问题已经解决了，感谢大佬的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月27日(星期一) 下午4:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microapp-store/linjiashop] 将图片存放到配置的目录下 (Issue #47)





 
自己随便创建，想创建到哪里就放到哪里，比如你在C盘创建了一个目录c:\upload,那你，就在系统参数表t_sys_cfg表里更新下，cfg_name=“system.file.upload.path”的那条记录
